"""Agregar favoritos de emprendimientos

Revision ID: 0b85b384e135
Revises: 9e4a71c4283c
Create Date: 2026-08-14 00:08:01.720140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b85b384e135'
down_revision = '9e4a71c4283c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    # Con nombre explicito: sin el, MySQL la llama favorites_ibfk_1 y SQLite no
    # le pone nombre, y b30b4ba8d199 (que la dropea para agregarle el CASCADE)
    # se queda sin un nombre que sirva en los dos motores.
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_favorites_post_id_posts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_favorite_user_post')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Solo drop_table: los drop_index que venian autogenerados fallan sobre
    # MySQL con "Cannot drop index 'ix_favorites_post_id': needed in a foreign
    # key constraint", porque ese indice sostiene la FK. Y es de los que dejan
    # la base a medio migrar: el de user_id llega a irse antes de que reviente
    # el otro, y como MySQL no tiene DDL transaccional no hay rollback.
    op.drop_table('favorites')
