"""Agregar is_banned a los usuarios

Revision ID: 0c6a050f0a19
Revises: e1e6eae6f924
Create Date: 2026-08-14 00:39:44.788603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6a050f0a19'
down_revision = 'e1e6eae6f924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
