"""Agregar imagen de portada al perfil

Revision ID: 499b808ef8ab
Revises: b30b4ba8d199
Create Date: 2026-08-14 01:35:22.943408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499b808ef8ab'
down_revision = 'b30b4ba8d199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
