"""Agregar categoria a los emprendimientos

Revision ID: 4f8b85a277a0
Revises: c7d7e62e0bea
Create Date: 2026-08-13 23:56:25.577177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8b85a277a0'
down_revision = 'c7d7e62e0bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), server_default='otros', nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
