"""Agregar contador de vistas a los emprendimientos

Revision ID: 6f4d273e25d2
Revises: c24e5fc659b9
Create Date: 2026-08-14 00:49:00.592042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4d273e25d2'
down_revision = 'c24e5fc659b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('views_count')

    # ### end Alembic commands ###
