"""Agregar busqueda de personal y postulaciones

Revision ID: 88a6ceb0bb22
Revises: c7d92f4a1b83
Create Date: 2026-09-11 14:07:01.964148

Un emprendimiento publica que busca a alguien para trabajar, y quien entra a su
ficha se postula con un formulario corto. Dos tablas:

  busquedas_personal   el aviso, con su toggle
  postulaciones        lo que manda cada postulante, colgado del aviso

UNIQUE(post_id, cupo_activa) es el unique parcial portable, el mismo que
service_requests.cupo_pendiente: cupo_activa vale 1 mientras el aviso esta
publicado y NULL cuando se cierra, y como los dos motores ignoran los NULL en
un UNIQUE, la regla termina siendo "una sola busqueda activa por
emprendimiento" sin impedir que haya todas las cerradas que hagan falta.

Los textos son String(n) y no Text a proposito, aunque descripcion y
experiencia sean parrafos: sobre los cuatro corre validar_largo, y largo_de()
sobre una columna Text devuelve None (H4).

Las dos FK nacen con ON DELETE CASCADE, que desde b2b97d078fb2 es la regla del
proyecto: borrar el emprendimiento se lleva sus busquedas y sus postulaciones,
y borrar al usuario se lleva las suyas.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a6ceb0bb22'
down_revision = 'c7d92f4a1b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busquedas_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('puesto', sa.String(length=120), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('cupo_activa', sa.Integer(), nullable=True),
    sa.Column('vistas_sin_postulacion', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cerrada_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_busquedas_personal_post_id_posts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'cupo_activa', name='uq_busquedas_personal_activa')
    )
    with op.batch_alter_table('busquedas_personal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_busquedas_personal_activa'), ['activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_busquedas_personal_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_busquedas_personal_post_id'), ['post_id'], unique=False)

    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('busqueda_id', sa.Integer(), nullable=False),
    sa.Column('postulante_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=False),
    sa.Column('experiencia', sa.String(length=600), nullable=False),
    sa.Column('disponibilidad', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['busqueda_id'], ['busquedas_personal.id'], name='fk_postulaciones_busqueda_id_busquedas_personal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postulante_id'], ['users.id'], name='fk_postulaciones_postulante_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('busqueda_id', 'postulante_id', name='uq_postulaciones_una_por_busqueda')
    )
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postulaciones_busqueda_id'), ['busqueda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postulaciones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_postulaciones_postulante_id'), ['postulante_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """Borra las dos tablas, y SOLO las tablas.

    Sin los drop_index que habia escrito el autogenerate, y no es cosmetico:
    contra MySQL el downgrade moria en la primera linea con el error 1553
    ("Cannot drop index 'ix_postulaciones_postulante_id': needed in a foreign
    key constraint"), porque un DROP INDEX sobre la columna de una foreign key
    esta prohibido mientras la FK exista. Se comprobo bajando el paso AISLADO
    (88a6ceb0bb22 -> c7d92f4a1b83) en una base descartable.

    En SQLite pasaba sin chistar, que es por lo que se colo: la suite no baja
    migraciones contra MySQL.

    Y los drop_index no hacen falta: DROP TABLE se lleva los indices de la
    tabla en los dos motores. El orden si importa, postulaciones antes que
    busquedas_personal, porque la FK apunta para ese lado.
    """
    op.drop_table('postulaciones')
    op.drop_table('busquedas_personal')
