"""Agregar read_at a los mensajes para el contador de notificaciones

Revision ID: 9e4a71c4283c
Revises: 4f8b85a277a0
Create Date: 2026-08-14 00:01:50.607023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4a71c4283c'
down_revision = '4f8b85a277a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
