"""Agregar reportes de contenido

Revision ID: c24e5fc659b9
Revises: 0c6a050f0a19
Create Date: 2026-08-14 00:46:13.673367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24e5fc659b9'
down_revision = '0c6a050f0a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(post_id IS NOT NULL) != (review_id IS NOT NULL)', name='ck_report_target_xor'),
    # Las FK van con nombre explicito. Sin nombre, cada motor les pone el suyo
    # (MySQL las llama reports_ibfk_1/2/3, SQLite no les pone ninguno), asi que
    # una migracion posterior que necesite dropearlas no tiene un nombre que
    # sirva en los dos: es lo que rompio d09128dd029c, que quedo con los
    # nombres de MySQL hardcodeados y no podia correr sobre SQLite.
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_reports_post_id_posts'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name='fk_reports_reporter_id_users'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='fk_reports_review_id_reviews'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Solo drop_table: los drop_index que venian autogenerados fallan sobre
    # MySQL con "Cannot drop index 'ix_reports_review_id': needed in a foreign
    # key constraint", porque esos indices sostienen las tres FK. Dropear la
    # tabla se lleva sus indices igual, en los dos motores.
    op.drop_table('reports')
