"""Agregar ON DELETE CASCADE a las FK de reports

Revision ID: d09128dd029c
Revises: 6f4d273e25d2
Create Date: 2026-08-14 01:04:09.735197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09128dd029c'
down_revision = '6f4d273e25d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reports_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reports_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_3'), 'reviews', ['review_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_1'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
